run:
  deadline: "3m"
  skip-dirs:
    - pkg/graph

linters:
  enable-all: false
  enable:
    - golint
    - gosec
    - unconvert
    - misspell

# Workaround for golangci/golangci-lint#658
issues:
  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
