language: go
sudo: false

go:
  - stable
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.5

script:
  - go test ./...
  - >
    ./bin/golangci-lint run --skip-dirs=pkg/graph
    --enable=golint --enable=gosec --enable=unconvert
    --enable=misspell

notifications:
  email:
    on_success: never
